liquid_domain: liquid.example.org
devel: true
use_https: false

# Default of different git repos checked out on the images
git_repo_versions:
  hoover:
    setup: master
    testdata: master
    snoop: master
    search: master
    ui: master
  hypothesis:
    h: 53046f652c801b85e792c0020fa71f7493b249da
    h_client_build: master
  discover: master
  liquid_core: first-boot-hotspot
  setup: master
  web_ui: master
