liquid_domain: liquid.example.org
devel: false
use_https: false

# Default of different git repos checked out on the images
git_repo_versions:
  hoover:
    setup: master
    snoop2: master
    search: master
    ui: master
    magic_definitions: master
  hypothesis:
    h: master
    h_client_build: master
  discover: master
  liquid_core: master
  setup: davros-sync
  web_ui: master
  ui_templates: master
  dokuwiki_plugin_oauth: master
