# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  # Fix passthrough of bad locale
  ENV['LC_ALL']="en_US.UTF-8"
  ENV['LANG']="en_US.UTF-8"
  ENV['LANGUAGE']="en_US.UTF-8"

  # tell apt-get not to expect a tty
  ENV['DEBIAN_FRONTEND']="noninteractive"

  # provider-specific configurations
  def configure_vbox_provider(config)
    config.vm.provider :virtualbox do |vbox, override|

      override.vm.box = "bento/ubuntu-16.04"

      override.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true

      # this maps the current folder to a hidden folder in the vagrant user's
      # home directory
      override.vm.synced_folder ".", "/home/vagrant/.VagrantSetup"
      override.vm.synced_folder "../../", "/home/vagrant/setup"

      # add time sync stuff
      vbox.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 500 ]

    end
  end

  # proider-specific configuration
  configure_vbox_provider(config)

  def create_provision_command_set(hostname)
    <<-SHELL

    # set up locale
    export LC_ALL="en_US.UTF-8"
    export LANG="en_US.UTF-8"
    export LANGUAGE="en_US.UTF-8"
    sudo locale-gen en_US.UTF-8

    # install dependencies
    sudo apt-get install software-properties-common python-software-properties
    sudo apt-add-repository ppa:ansible/ansible
    sudo apt-get update
    sudo apt-get install -y ansible
    sudo apt-get install -y git

    # get liquidinvestigations/setup ansible scripts
    export liquid_dev_root=$HOME/Repository/Liquid
    git clone https://github.com/liquidinvestigations/setup $liquid_dev_root/setup
    cd $liquid_dev_root/setup/ansible
    git checkout avahi-daemon
    git pull

    # fill out the liquid_domain and run ansible
    touch vars/config.yml
    echo "liquid_domain: '#{hostname}'" > vars/config.yml
    sudo ansible-playbook server.yml

    # pull the liquid-core version that runs zeroconf
    cd /opt/liquid-core/liquid-core
    sudo git checkout use-zeroconf
    sudo git pull
    # install additional requirements
    sudo bash -c 'cd /opt/liquid-core/liquid-core; source ../venv/bin/activate; pip install -r requirements.txt'

    sudo /opt/common/boot.sh
    sudo supervisorctl update

    sudo service nginx reload

    SHELL
  end

  # provisioning (currently provider-agnostic)
  config.vm.provision "shell", privileged: false, name: "Install dependencies", inline: create_provision_command_set("vagrant-box-one.liquid")

end
