---
- name: Create the invoke-hook script
  template:
    src: libexec/invoke-hook
    dest: /opt/common/libexec/invoke-hook
    mode: 0755

- name: Create /opt/common/hooks directory
  file:
    path: /opt/common/hooks
    state: directory

- name: Create the hooks .d directories
  file:
    dest: /opt/common/hooks/{{ item }}.d
    state: directory
  with_items:
    - user-created
    - user-passwd
    - user-deleted
