---
- name: Create the invoke-hook script
  template:
    src: libexec/invoke-hook
    dest: /opt/common/libexec/invoke-hook
    mode: 0755

- name: Create /opt/common/hooks directory
  file:
    path: /opt/common/hooks
    state: directory

- name: Create folders for hooks
  file:
    path: /opt/common/hooks/{{ item }}.d
    state: directory
    mode: 0755
  with_items:
    - user-created
    - user-deleted
    - user-passwd

- name: Configure sudo rights for liquid-apps
  copy:
    src: sudoers.d/liquid-hooks
    dest: /etc/sudoers.d/liquid-hooks
