---
- name: Update all packages
  apt:
    update_cache: yes
    cache_valid_time: 14400
    # TODO create a flag for apt-get upgrade
    #upgrade: dist
  tags:
    - prerequisites

- name: Set up machine hostname
  hostname:
    name: "{{ liquid_domain.split('.')[0] }}"
  tags:
    - configure

- name: Put hostname in /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: '127.0.0.1 {{ liquid_domain.split(".")[0] }}'
    state: present
  tags:
    - configure

- name: Install base packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - curl
    - git
    - apt-transport-https
    - supervisor
    - nginx
    - python3
    - python-virtualenv
    - iptables
    - build-essential
    - default-jre-headless
    - postgresql
    - postgresql-contrib
    - postgresql-server-dev-all
    - python-psycopg2 # so that ansible can manage postgres users and dbs
    - openssh-server
  tags:
    - prerequisites

- name: Remove cloud-init if it's installed
  apt:
    name: cloud-init
    state: absent
    purge: yes
  tags:
    - prerequisites

- name: apt-get clean
  command: apt-get -y clean

- name: Enable supervisor
  service:
    name: supervisor
    enabled: yes

- name: Create liquid system user
  user:
    name: liquid
    shell: /bin/bash

- name: Create the supervisor global config
  template:
    src: supervisor/supervisor.conf
    dest: /etc/supervisor/supervisor.conf

- name: Create /var/lib/liquid directory structure
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /var/lib/liquid
    - /var/lib/liquid/conf
    - /var/lib/liquid/https
    - /var/lib/liquid/https/nginx
    - /var/lib/liquid/https/certs

- name: Create common folder
  file:
    path: /opt/common
    state: directory
    mode: 0755

- name: Create the initialization script
  template:
    src: initialize.sh
    dest: /opt/common/initialize.sh
    mode: 0755

- name: Create folder for init scripts of other modules
  file:
    path: /opt/common/initialize.d
    state: directory
    mode: 0755

- name: Create the common initialization script
  copy:
    src: initialize.d/common
    dest: /opt/common/initialize.d/00-common
    mode: 0755

- name: Create the boot script
  template:
    src: boot.sh
    dest: /opt/common/boot.sh
    mode: 0755

- name: Start boot script
  lineinfile:
    dest: /etc/rc.local
    insertbefore: "exit 0"
    line: "/opt/common/boot.sh >> /var/log/rc.local.log 2>&1"

- name: Nginx hash bucket size
  lineinfile:
    dest: /etc/nginx/nginx.conf
    regexp: 'server_names_hash_bucket_size'
    line: '	server_names_hash_bucket_size 64;'

- name: nginx default site conf
  template:
    src: nginx/default
    dest: /etc/nginx/sites-enabled/default

- name: remove default nginx site html page
  file:
    path: "/var/www/html/{{ item }}"
    state: absent
  with_fileglob:
    - "index.*.html"

- name: nginx default site html page
  template:
    src: nginx/index.html
    dest: /var/www/html/index.html
  tags:
    - configure

- name: nginx https settings
  copy:
    src: nginx/https.conf
    dest: /var/lib/liquid/https/nginx/https.conf

- name: Create /opt/common/libexec directory
  file:
    path: /opt/common/libexec
    state: directory

- import_tasks: tasks/hooks.yml

- name: Create the firewall script
  copy:
    src: libexec/firewall
    dest: /opt/common/libexec/firewall
    mode: 0755

- when: ansible_architecture == 'x86_64'
  name: "Cloud: Set up ens3 interface as dhcp"
  copy:
    content: "auto ens3\niface ens3 inet dhcp\n"
    dest: /etc/network/interfaces.d/ens3.cfg

- name: Clone the setup repo in /opt/setup
  git:
    repo: https://github.com/liquidinvestigations/setup.git
    dest: /opt/setup
    version: "{{ git_repo_versions.setup }}"
    update: false
