---
- name: Install base packages
  apt: name={{ item }} state=latest
  with_items:
    - curl
    - git
    - supervisor
    - nginx
    - python3
    - python-virtualenv
    - iptables

- name: Create liquid user
  user:
    name: liquid
