---
- name: Update all packages
  apt:
    update_cache: yes
    cache_valid_time: 14400
    upgrade: dist

- name: Install base packages
  apt: name={{ item }} state=latest
  with_items:
    - curl
    - git
    - supervisor
    - nginx
    - python3
    - python-virtualenv
    - iptables
    - build-essential
    - openjdk-7-jre-headless
    - postgresql
    - postgresql-contrib
    - postgresql-server-dev-all
    - python-psycopg2 # so that ansible can manage postgres users and dbs

- name: apt-get clean
  command: apt-get -y clean

- name: Enable supervisor
  service:
    name: supervisor
    enabled: yes

- name: Create liquid system user
  user:
    name: liquid

- name: Create common folder
  file: path=/opt/common state=directory mode=0755

- name: Create the initialization script
  template: src=initialize.sh
            dest=/opt/common/initialize.sh
            mode=755

- name: Create folder for init scripts of other modules
  file: path=/opt/common/initialize.d state=directory mode=0755
