---
- name: Update all packages
  apt:
    update_cache: yes
    cache_valid_time: 14400
    upgrade: dist

- name: Install base packages
  apt: name={{ item }} state=latest
  with_items:
    - curl
    - git
    - supervisor
    - nginx
    - python3
    - python-virtualenv
    - iptables

- name: apt-get clean
  command: apt-get -y clean

- name: Enable supervisor
  service:
    name: supervisor
    enabled: yes

- name: Create liquid user
  user:
    name: liquid
