---
- name: Update all packages
  apt:
    update_cache: yes
    cache_valid_time: 14400
    upgrade: dist

- name: Install base packages
  apt: name={{ item }} state=latest
  with_items:
    - curl
    - git
    - supervisor
    - nginx
    - python3
    - python-virtualenv
    - iptables
    - build-essential
    - postgresql
    - postgresql-contrib
    - postgresql-server-dev-all
    - python-psycopg2 # so that ansible can manage postgres users and dbs

- name: apt-get clean
  command: apt-get -y clean

- name: Enable supervisor
  service:
    name: supervisor
    enabled: yes

- name: Create liquid system user
  user:
    name: liquid

- name: Create liquid postgres user
  become: yes
  become_user: postgres
  postgresql_user:
    name: liquid
