---
- name: Update all packages
  apt:
    update_cache: yes
    cache_valid_time: 14400
    # TODO create a flag for apt-get upgrade
    #upgrade: dist

- name: Set up machine hostname
  hostname:
    name: "{{ liquid_domain.split('.')[0] }}"

- name: Put hostname in /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: '127.0.0.1 {{ liquid_domain.split(".")[0] }}'
    state: present

- name: Put FQDN in /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: '127.0.0.1 {{ liquid_domain }}'
    state: present

- name: Install base packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - curl
    - git
    - apt-transport-https
    - supervisor
    - nginx
    - python3
    - python-virtualenv
    - iptables
    - build-essential
    - default-jre-headless
    - postgresql
    - postgresql-contrib
    - postgresql-server-dev-all
    - python-psycopg2 # so that ansible can manage postgres users and dbs

- name: apt-get clean
  command: apt-get -y clean

- name: Enable supervisor
  service:
    name: supervisor
    enabled: yes

- name: Create liquid system user
  user:
    name: liquid
    shell: /bin/bash

- name: Create the supervisor global config
  template:
    src: supervisor/supervisor.conf
    dest: /etc/supervisor/supervisor.conf

- name: Create /var/lib/liquid directory
  file:
    path: /var/lib/liquid
    state: directory

- name: Create /var/lib/liquid/conf directory
  file:
    path: /var/lib/liquid/conf
    state: directory

- name: Create common folder
  file:
    path: /opt/common
    state: directory
    mode: 0755

- name: Create the initialization script
  template:
    src: initialize.sh
    dest: /opt/common/initialize.sh
    mode: 0755

- name: Create folder for init scripts of other modules
  file:
    path: /opt/common/initialize.d
    state: directory
    mode: 0755

- name: Create the boot script
  template:
    src: boot.sh
    dest: /opt/common/boot.sh
    mode: 0755

- name: Start boot script
  lineinfile:
    dest: /etc/rc.local
    insertbefore: "exit 0"
    line: "/opt/common/boot.sh >> /var/log/rc.local.log 2>&1"

- name: Nginx hash bucket size
  lineinfile:
    dest: /etc/nginx/nginx.conf
    regexp: 'server_names_hash_bucket_size'
    line: '	server_names_hash_bucket_size 64;'

- name: nginx default site conf
  template:
    src: nginx/default
    dest: /etc/nginx/sites-enabled/default

- name: remove default nginx site html page
  file:
    path: "/var/www/html/{{ item }}"
    state: absent
  with_fileglob:
    - "index.*.html"

- name: nginx default site html page
  template:
    src: nginx/index.html
    dest: /var/www/html/index.html

- name: Create /opt/common/libexec directory
  file:
    path: /opt/common/libexec
    state: directory

- include: tasks/hooks.yml

- name: Create the firewall script
  copy:
    src: libexec/firewall
    dest: /opt/common/libexec/firewall
    mode: 0755

- name: Run the firewall script at boot
  lineinfile:
    dest: /etc/rc.local
    insertbefore: "exit 0"
    line: "/opt/common/libexec/firewall >> /var/log/rc.local.log 2>&1"
