---
- block:
  - name: Import GPG key
    apt_key:
      url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x5BB92C09DB82666C
      id: "DB82666C"
      state: present

  - name: Add apt source
    apt_repository:
      repo: 'deb http://ppa.launchpad.net/fkrull/deadsnakes/ubuntu trusty main'
      state: present

  - name: Install python3.6
    apt:
      pkg:
        - python3.6
      state: installed

  - name: Create symlink /usr/local/bin/python3
    file:
      src: /usr/bin/python3.6
      dest: /usr/local/bin/python3
      state: link

  when: ansible_distribution_release == 'jessie'
