---
- name: Add deadsnakes repo
  apt_repository:
    repo: "ppa:deadsnakes/ppa"
  tags:
    - prerequisites

- name: Install python3.6
  apt:
    pkg:
      - python3.6
      - python3.6-dev
    state: installed
  tags:
    - prerequisites

- name: Create symlink /usr/local/bin/python3
  file:
    src: /usr/bin/python3.6
    dest: /usr/local/bin/python3
    state: link
  tags:
    - prerequisites
