---
- when: ansible_architecture == 'x86_64'
  block:
  - name: Add deadsnakes repo
    apt_repository:
      repo: "ppa:deadsnakes/ppa"

  - name: Install python3.6
    apt:
      pkg:
        - python3.6
        - python3.6-dev
      state: installed

  - name: Create symlink /usr/local/bin/python3
    file:
      src: /usr/bin/python3.6
      dest: /usr/local/bin/python3
      state: link

  tags:
    - prerequisites

- when: ansible_architecture == 'aarch64'
  block:
  - name: "python3.6.4 runtime&build dependencies"
    apt:
      name: "{{ item }}"
      state: latest
    with_items:
      - build-essential
      - tk-dev
      - libncurses5-dev
      - libncursesw5-dev
      - libreadline6-dev
      - libdb5.3-dev
      - libgdbm-dev
      - libsqlite3-dev
      - libssl-dev
      - libbz2-dev
      - libexpat1-dev
      - liblzma-dev
      - zlib1g-dev

  - name: "Download python3.6.4"
    get_url:
      url: "https://www.python.org/ftp/python/3.6.4/Python-3.6.4.tar.xz"
      dest: /tmp/Python-3.6.4.tar.xz

  - name: "Unarchive python3.6.4"
    unarchive:
      src: /tmp/Python-3.6.4.tar.xz
      dest: /tmp/
      copy: false
    creates: /tmp/Python-3.6.4

  - name: "configure python3.6.4 build"
    command: ./configure
    args:
      chdir: "/tmp/Python-3.6.4"
      creates: "/tmp/Python-3.6.4/Makefile"

  - name: "build python3.6.4"
    command: make -j4
    args:
      chdir: "/tmp/Python-3.6.4"
      creates: "/tmp/Python-3.6.4/python"

  - name: "install python3.6.4"
    make:
      chdir: "/tmp/Python-3.6.4"
      target: altinstall

  - name: Create symlink /usr/local/bin/python3
    file:
      src: /usr/local/bin/python3.6
      dest: /usr/local/bin/python3
      state: link

  tags:
    - prerequisites
