---
- block:
  - name: Import GPG key
    apt_key:
      url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x5BB92C09DB82666C
      id: "DB82666C"
      state: present

  - name: Add apt source
    apt_repository:
      repo: 'deb http://ppa.launchpad.net/fkrull/deadsnakes/ubuntu trusty main'
      state: present

  - name: Install python3.6
    apt:
      pkg:
        - python3.6
      state: installed

  - name: Create symlink /usr/local/bin/python3
    file:
      src: /usr/bin/python3.6
      dest: /usr/local/bin/python3
      state: link

  - name: Download virtualenv 15.1.0
    unarchive:
      src: https://pypi.python.org/packages/d4/0c/9840c08189e030873387a73b90ada981885010dd9aea134d6de30cd24cb8/virtualenv-15.1.0.tar.gz
      dest: /opt
      remote_src: yes
      creates: /opt/virtualenv-15.1.0

  - name: Install virtualenv 15.1.0 from source
    shell: "python3 setup.py install"
    args:
      executable: /bin/bash
      chdir: /opt/virtualenv-15.1.0


  when: ansible_distribution_release == 'jessie'
