---
- name: Download pre-built client code
  git:
    repo: https://github.com/liquidinvestigations/h-client-build.git
    dest: /opt/hypothesis/h-client-build
    version: "{{ git_repo_versions.hypothesis.h_client_build }}"

- name: Bake the boot script
  environment:
    ASSET_ROOT: "{{ http_scheme }}://client.hypothesis.{{ liquid_domain }}/"
    SIDEBAR_APP_URL: "{{ http_scheme }}://hypothesis.{{ liquid_domain }}/app.html"
  command: ./bake.py
  args:
    chdir: /opt/hypothesis/h-client-build
  tags:
    - configure

- name: Create the nginx configuration file
  template:
    src: nginx/hypothesis-client.conf
    dest: /etc/nginx/sites-enabled/hypothesis-client.conf
  tags:
    - configure
