---
- name: Install system dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - python2.7-dev
    - rabbitmq-server
    - libffi-dev
  tags:
    - prerequisites

- name: Create the top folder
  file:
    path: /opt/hypothesis
    state: directory
    mode: 0755

- name: Download the source code
  git:
    repo: https://github.com/hypothesis/h.git
    dest: /opt/hypothesis/h
    version: "{{ git_repo_versions.hypothesis.h }}"

- name: Change ownership of h folder
  file:
    path: /opt/hypothesis/h
    owner: liquid
    group: liquid

- name: Install virtualenv with latest setuptools and pip
  pip:
    name: ['setuptools', 'pip', 'pyparsing==2.1.10']
    extra_args: '--upgrade'
    virtualenv: /opt/hypothesis/venv
    virtualenv_python: python2

- name: Install requirements
  pip:
    chdir: /opt/hypothesis/h
    requirements: /opt/hypothesis/h/requirements.txt
    virtualenv: /opt/hypothesis/venv
    virtualenv_python: python2

- name: Install npm dependencies
  npm:
    path: /opt/hypothesis/h
    production: yes

- name: Rebuild node-sass
  command: npm rebuild node-sass
  args:
    chdir: /opt/hypothesis/h
    creates: node_modules/node-sass/vendor

- name: Build assets
  command: node_modules/.bin/gulp build
  args:
    chdir: /opt/hypothesis/h
    creates: build

- import_tasks: tasks/client.yml

- name: Download elasticsearch v1
  unarchive:
    src: https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.2.tar.gz
    dest: /opt/hypothesis
    remote_src: yes
    creates: /opt/hypothesis/elasticsearch-1.7.2

- name: Write the elasticsearch configuration file
  template:
    src: elasticsearch-config/elasticsearch.yml
    dest: /opt/hypothesis/elasticsearch-1.7.2/config/elasticsearch.yml

- name: Change ownership of data and logs folders
  file:
    path: "/opt/hypothesis/elasticsearch-1.7.2/{{ item }}"
    owner: liquid
    group: liquid
    state: directory
    recurse: true
  with_items:
    - data
    - logs

- name: Install elasticsearch ICU plugin
  command: bin/plugin install elasticsearch/elasticsearch-analysis-icu/2.7.0
  args:
    chdir: /opt/hypothesis/elasticsearch-1.7.2
    creates: /opt/hypothesis/elasticsearch-1.7.2/plugins/analysis-icu

- name: Create the libexec folder
  file:
    path: /opt/hypothesis/libexec
    state: directory
    mode: 0755

- name: Create the elasticsearch run script
  template:
    src: libexec/elasticsearch
    dest: /opt/hypothesis/libexec/elasticsearch
    mode: 0755

- when: liquid_services.hypothesis.enabled
  block:
  - name: Create the hypothesis run helper
    template:
      src: libexec/run-h
      dest: /opt/hypothesis/libexec/run-h
      mode: 0755
  
  - name: Create the supervisor configuration file
    template:
      src: supervisor/hypothesis.conf
      dest: /etc/supervisor/conf.d/hypothesis.conf
  
  - name: Create the nginx configuration file
    template:
      src: nginx/hypothesis.conf
      dest: /etc/nginx/sites-enabled/hypothesis.conf
  
  - name: Subscribe to hooks
    copy:
      src: hooks/user
      dest: /opt/common/hooks/{{ item }}.d/hypothesis
      mode: 0755
    with_items:
      - user-created
      - user-passwd
      - user-deleted
  
  - name: Create the initialization script
    template:
      src: initialize.d/hypothesis.sh
      dest: /opt/common/initialize.d/23-hypothesis.sh
      mode: 0755

- when: not liquid_services.hypothesis.enabled
  name: Remove configuration files for disabled service
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /opt/hypothesis/libexec/run-h
    - /etc/supervisor/conf.d/hypothesis.conf
    - /etc/nginx/sites-enabled/hypothesis.conf
    - /opt/common/hooks/user-created.d/hypothesis
    - /opt/common/hooks/user-passwd.d/hypothesis
    - /opt/common/hooks/user-deleted.d/hypothesis
    - /opt/common/initialize.d/23-hypothesis.sh
  tags:
    - configure
