---
- name: Install system dependencies
  apt: name={{ item }} state=latest
  with_items:
    - python2.7-dev

- name: Create the top folder
  file: path=/opt/hypothesis state=directory mode=0755

- name: Download the source code
  git: repo=https://github.com/hypothesis/h.git
       dest=/opt/hypothesis/h

- name: Install virtualenv with latest setuptools and pip
  pip:
    name: ['setuptools', 'pip', 'pyparsing==2.1.5']
    extra_args: '--upgrade'
    virtualenv: /opt/hypothesis/venv
    virtualenv_python: python2

- name: Install requirements
  pip:
    chdir: /opt/hypothesis/h
    requirements: /opt/hypothesis/h/requirements.txt
    virtualenv: /opt/hypothesis/venv
    virtualenv_python: python2

- name: Set up database
  become: yes
  become_user: postgres
  postgresql_db:
    name: hypothesis
    owner: liquid

- name: Create uuid extension on database
  become: yes
  become_user: postgres
  postgresql_ext:
    name: uuid-ossp
    db: hypothesis

- name: Migrate database
  command: bin/hypothesis init
  become: yes
  become_user: liquid
  environment:
    PATH: "/opt/hypothesis/venv/bin:{{ ansible_env.PATH }}"
    DATABASE_URL: postgresql:///hypothesis
    APP_URL: "http://hypothesis.{{ liquid_domain }}"
  args:
    chdir: /opt/hypothesis/h
