---
- name: Install system dependencies
  apt: name={{ item }} state=latest
  with_items:
    - python2.7-dev

- name: Create the top folder
  file: path=/opt/hypothesis state=directory mode=0755

- name: Download the source code
  git: repo=https://github.com/hypothesis/h.git
       dest=/opt/hypothesis/h

- name: Install virtualenv with latest setuptools and pip
  pip:
    name: ['setuptools', 'pip', 'pyparsing==2.1.5']
    extra_args: '--upgrade'
    virtualenv: /opt/hypothesis/venv
    virtualenv_python: python2

- name: Install requirements
  pip:
    chdir: /opt/hypothesis/h
    requirements: /opt/hypothesis/h/requirements.txt
    virtualenv: /opt/hypothesis/venv
    virtualenv_python: python2

- name: Download elasticsearch v1
  unarchive:
    src: https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.2.tar.gz
    dest: /opt/hypothesis
    remote_src: yes
    creates: /opt/hypothesis/elasticsearch-1.7.2

- name: Write the elasticsearch configuration file
  template: src=elasticsearch-config/elasticsearch.yml
            dest=/opt/hypothesis/elasticsearch-1.7.2/config/elasticsearch.yml

- name: Change ownership of data and logs folders
  file:
    path: "{{ item }}"
    owner: liquid
    group: liquid
    recurse: true
  with_items:
    - /opt/hypothesis/elasticsearch-1.7.2/data
    - /opt/hypothesis/elasticsearch-1.7.2/logs

- name: Install elasticsearch ICU plugin
  command: bin/plugin install elasticsearch/elasticsearch-analysis-icu/2.7.0
  args:
    chdir: /opt/hypothesis/elasticsearch-1.7.2
    creates: /opt/hypothesis/elasticsearch-1.7.2/plugins/analysis-icu

- name: Create the initialization script
  template: src=initialize.d/hypothesis.sh
            dest=/opt/common/initialize.d/hypothesis.sh
            mode=755

- name: Create the libexec folder
  file: path=/opt/hypothesis/libexec state=directory mode=0755

- name: Create the elasticsearch run script
  template: src=libexec/elasticsearch
            dest=/opt/hypothesis/libexec/elasticsearch
            mode=755

- name: Create the hypothesis run helper
  template: src=libexec/run-h
            dest=/opt/hypothesis/libexec/run-h
            mode=755

- name: Create the supervisor configuration file
  template: src=supervisor/hypothesis.conf
            dest=/etc/supervisor/conf.d/hypothesis.conf
