#!/bin/bash
set -e

cd /opt/hypothesis/h
source ../venv/bin/activate
source ../libexec/secrets.sh

export PYTHONPATH="${PWD}"
export DATABASE_URL="postgresql:///hypothesis"
export ELASTICSEARCH_HOST="http://127.0.0.1:14312"

source /var/lib/liquid/conf/hypothesis/run-h-vars.sh

exec "$@"
