---
- import_tasks: tasks/authproxy.yml

- name: Download the source code
  git:
    repo: https://github.com/mnutt/davros.git
    dest: /opt/davros/davros
    version: master
  tags:
    - prerequisites

- name: Set up file permissions
  file:
    path: /opt/davros/davros
    state: directory
    owner: liquid-apps
    group: liquid-apps
    recurse: true
  tags:
    - prerequisites

- name: Install dependencies and run build
  shell: |
    set -e
    set -x
    npm set progress=false
    npm set color=false
    npm install
    ./node_modules/bower/bin/bower --no-color install
    ./node_modules/ember-cli/bin/ember build
  args:
    chdir: /opt/davros/davros
  become: yes
  become_user: liquid-apps
  tags:
    - prerequisites

- name: Create empty data dir for davros-sync
  file:
    path: "{{item}}"
    state: directory
    owner: liquid-apps
    group: liquid-apps
  with_items:
    - "/var/lib/liquid/data"
    - "/var/lib/liquid/data/davros-sync"

- when: liquid_services.davros.enabled
  block:
  - name: Create supervisor config
    copy:
      src: supervisor/davros.conf
      dest: /etc/supervisor/conf.d/davros.conf
  
  - name: Create nginx config
    template:
      src: nginx/davros.conf
      dest: /etc/nginx/sites-enabled/davros.conf
  
  - name: Copy the initialization script
    template:
      src: initialize.d/davros.sh
      dest: /opt/common/initialize.d/20-davros.sh
      mode: 0755
  tags:
    - configure

- when: not liquid_services.davros.enabled
  name: Remove configuration files for disabled service
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/supervisor/conf.d/davros.conf
    - /etc/nginx/sites-enabled/davros.conf
    - /opt/common/initialize.d/20-davros.sh
  tags:
    - configure
