---
- import_tasks: tasks/authproxy.yml

- name: Download the source code
  git:
    repo: https://github.com/mnutt/davros.git
    dest: /opt/davros/davros
    version: master

- name: Install dependencies and run build
  shell: |
    npm install
    ./node_modules/bower/bin/bower install
    ./node_modules/ember-cli/bin/ember build
  args:
    chdir: /opt/davros/davros

- name: Create supervisor config
  copy:
    src: supervisor/davros.conf
    dest: /etc/supervisor/conf.d/davros.conf

- name: Create nginx config
  template:
    src: nginx/davros.conf
    dest: /etc/nginx/sites-enabled/davros.conf
  tags:
    - configure

- name: Copy the initialization script
  template:
    src: initialize.d/davros.sh
    dest: /opt/common/initialize.d/20-davros.sh
    mode: 0755
  tags:
    - configure

- name: Create empty data dir for davros-sync
  file:
    path: "{{item}}"
    state: directory
    owner: liquid
    group: liquid
  with_items:
    - "/var/lib/liquid/data"
    - "/var/lib/liquid/data/davros-sync"
