liquid_domain: liquid.example.org

liquid_vpn: 
  server: 
    enabled: false
  client: 
    config: null
    enabled: false

liquid_lan:
  dhcp_range: "10.103.0.100,10.103.0.200,72h"
  ip: "10.103.0.1"
  netmask": "255.255.255.0"
  eth: false
  hotspot:
    ssid: null
    password: null

liquid_services:
  davros:
    enabled: true
  dokuwiki:
    enabled: true
  hoover:
    enabled: true
  hypothesis:
    enabled: true
  matrix:
    enabled: true
liquid_ssh:
  authorized_keys: []
  enabled: true
  port: 22

devel: false
use_https: false
http_scheme: "{{ 'https' if use_https else 'http' }}"

# Default of different git repos checked out on the images
git_repo_versions:
  hoover:
    setup: snoop2
    snoop2: master
    search: master
    ui: master
  hypothesis:
    h: 53046f652c801b85e792c0020fa71f7493b249da
    h_client_build: master
  discover: master
  liquid_core: master
  setup: master
  web_ui: master
  ui_templates: master

web_ui_override: false
web_ui_override_path: "/home/liquid/web-ui"
web_ui_override_port: 4200
