liquid_domain: liquid.local
devel: false
liquid_core_secret_key: "-- secret key here --"
discover_secret_key: "-- secret key here --"
davros_authproxy_secret_key: "-- secret key here --"
use_https: false
