#!/bin/bash
set -e

source /var/lib/liquid/conf/liquid_domain.sh

username="$1"
password="$2"
EMAIL="$username@$LIQUID_DOMAIN"

unset DJANGO_SETTINGS_MODULE
exec /opt/hypothesis/libexec/run-h bin/hypothesis user add \
  --username "$username" \
  --email "$EMAIL" \
  --password "$password"
