---
- import_tasks: tasks/docker.yml

- name: Set permissions on the cache folder
  file:
    path: /opt/hoover/cache
    state: directory
    mode: 0755
    owner: liquid
    group: liquid
    recurse: true

- name: Create the libexec folder
  file:
    path: /opt/hoover/libexec
    state: directory
    mode: 0755

- name: Copy scripts
  copy:
    src: libexec/{{ item }}
    dest: /opt/hoover/libexec/{{ item }}
    mode: 0755
  with_items:
    - import_testdata
    - build_ui

- name: Create the initialization script
  template:
    src: initialize.d/hoover.sh
    dest: /opt/common/initialize.d/22-hoover.sh
    mode: 0755

- name: Clone the testdata repo
  git:
    repo: https://github.com/hoover/testdata.git
    dest: /opt/hoover/collections/testdata

- name: Create supervisor config
  copy:
    src: supervisor/hoover.conf
    dest: /etc/supervisor/conf.d/hoover.conf

- name: Create the nginx configuration file
  template:
    src: nginx/hoover.conf
    dest: /etc/nginx/sites-enabled/hoover.conf
