---
- apt_repository:
    repo: "{{item}}"
    filename: multiverse
  with_items:
    - 'deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse'
    - 'deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse'
  when: ansible_distribution == 'Ubuntu' and ansible_architecture == 'x86_64'
  tags:
    - prerequisites

- apt_repository:
    repo: "{{item}}"
    filename: multiverse
  with_items:
    - 'deb http://ports.ubuntu.com/ubuntu-ports {{ansible_distribution_release}} multiverse'
    - 'deb http://ports.ubuntu.com/ubuntu-ports {{ansible_distribution_release}}-updates multiverse'
  when: ansible_distribution == 'Ubuntu' and ansible_architecture in ['armv7l', 'aarch64']
  tags:
    - prerequisites

- name: Install required system packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - python-psycopg2
    - libmagic-dev
    - python3-dev
    - libxml2-dev
    - libxslt1-dev
    - p7zip-full
    - p7zip-rar
    - pst-utils
    - cpanminus # for cpanm ansible module
  tags:
    - prerequisites

- name: Install msgconvert from CPAN
  cpanm:
      name: Email::Outlook::Message
  tags:
    - prerequisites

- block:
  - name: Run hoover initial setup
    shell: "python3 <(curl -sL https://github.com/hoover/setup/raw/master/install.py)"
    environment:
      HOOVER_SETUP_BRANCH: "{{ git_repo_versions.hoover.setup }}"
      HOOVER_HOME: "/opt/hoover"
      HOOVER_BOOTSTRAP_NO_DB: "True"
      HOOVER_ALLOWED_HOSTS: "hoover.{{ liquid_domain }}"
      HOOVER_ES_URL: "http://localhost:14352"
      HOOVER_TIKA_URL: "http://localhost:15423"
    args:
      executable: /bin/bash
      chdir: /opt
      creates: /opt/hoover
  rescue:
    - name: Delete the hoover folder after failed install attempt
      shell: "rm -rf /opt/hoover"
    - name: Fail the task because Hoover failed to install
      command: /bin/false

- name: Update source code for hoover search
  git:
    repo: https://github.com/hoover/search.git
    dest: /opt/hoover/search
    version: "{{ git_repo_versions.hoover.search }}"

- name: Update source code for hoover snoop
  git:
    repo: https://github.com/hoover/snoop.git
    dest: /opt/hoover/snoop
    version: "{{ git_repo_versions.hoover.snoop }}"

- name: Update source code for hoover ui
  git:
    repo: https://github.com/hoover/ui.git
    dest: /opt/hoover/ui
    version: "{{ git_repo_versions.hoover.ui }}"

- name: Download elasticsearch v2
  unarchive:
    src: https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-2.4.3.tar.gz
    dest: /opt/hoover
    remote_src: yes
    creates: /opt/hoover/elasticsearch-2.4.3

- name: Write the elasticsearch configuration file
  template:
    src: elasticsearch-config/elasticsearch.yml
    dest: /opt/hoover/elasticsearch-2.4.3/config/elasticsearch.yml

- name: Change ownership of elasticsearch data and logs folders
  file:
    path: "/opt/hoover/elasticsearch-2.4.3"
    owner: liquid
    group: liquid
    state: directory
    recurse: true

- name: Download Apache Tika
  get_url:
    dest: /opt/hoover/
    url: http://apache.javapipe.com/tika/tika-server-1.16.jar

- name: Create the supervisor configuration file
  template:
    src: supervisor/hoover.conf
    dest: /etc/supervisor/conf.d/hoover.conf

- name: Create the nginx configuration file
  template:
    src: nginx/hoover.conf
    dest: /etc/nginx/sites-enabled/hoover.conf
  tags:
    - configure

- name: Create the libexec folder
  file:
    path: /opt/hoover/libexec
    state: directory
    mode: 0755

- name: Create libexec scripts
  copy:
    src: "libexec/{{ item }}"
    dest: "/opt/hoover/libexec/{{ item }}"
    mode: 0755
  with_items:
    - elasticsearch
    - runserver-search
    - runserver-snoop
    - snoop-updater
    - search-updater
    - snoop-worker
    - tika

- name: Set permissions on the cache folder
  file:
    path: /opt/hoover/cache
    state: directory
    mode: 0755
    owner: liquid
    group: liquid
    recurse: true

- name: Create the initialization script
  template:
    src: initialize.d/hoover.sh
    dest: /opt/common/initialize.d/22-hoover.sh
    mode: 0755
  tags:
    - configure

- name: Create the davros sync script
  template:
    src: initialize.d/import-davros-sync.sh
    dest: /opt/common/initialize.d/41-hoover-import-davros-sync.sh
    mode: 0755

- name: Clone the testdata repo
  git:
    repo: https://github.com/hoover/testdata.git
    dest: /opt/hoover/testdata
    version: "{{ git_repo_versions.hoover.testdata }}"

- name: Create the testing_local.py config for snoop
  copy:
    src: snoop-testing-local.py
    dest: /opt/hoover/snoop/snoop/site/settings/testing_local.py

- name: Create the local.py config for snoop
  copy:
    src: snoop-local.py
    dest: /opt/hoover/snoop/snoop/site/settings/local.py

- name: Touch the secret_key.py config for snoop
  file:
    dest: /opt/hoover/snoop/snoop/site/settings/secret_key.py
    owner: liquid
    group: liquid
    state: touch

- name: Create the local.py config for search
  template:
    src: search-local.py
    dest: /opt/hoover/search/hoover/site/settings/local.py
    owner: liquid
    group: liquid
  tags:
    - configure

- name: Touch the secret_key.py config for search
  file:
    dest: /opt/hoover/search/hoover/site/settings/secret_key.py
    owner: liquid
    group: liquid
    state: touch

- name: Touch the oauth.py config for search
  file:
    dest: /opt/hoover/search/hoover/site/settings/oauth.py
    owner: liquid
    group: liquid
    state: touch
