---
- name: Import Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: Set up Docker repository
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    filename: docker

- name: Install docker
  apt: name={{ item }} state=latest
  with_items:
    - docker-ce
    - docker-compose
