---
- name: Install the board version of the liquid toolkit on the local system
  hosts: local
  vars_files:
    - ['vars/defaults.yml', 'vars/config.yml']
  roles:
    - common
    - devel
    - liquid-core
    - hotspot
