---
- name: Install the board version of the liquid toolkit in chroot
  hosts: image
  vars:
    build_docker_images: false
    devel: false
  roles:
    - common
    - devel
    - docker
    - node6
    - python3
    - systeml
    - liquid-core
    - hotspot
    - hoover
    - discover
    - hypothesis
    - dokuwiki
