---
- name: Install the server version of the Liquid Investigations toolkit
  hosts: all
  vars_files:
    - vars/defaults.yml
    - vars/config.yml
  roles:
    - common
    - devel
    - python3
    - network
    - discover
    - liquid-core
    - node6
    - web-ui
    - {tags: ['apps'], role: hoover}
    - {tags: ['apps'], role: hypothesis}
    - {tags: ['apps'], role: dokuwiki}
    - {tags: ['apps'], role: matrix}
    - {tags: ['apps'], role: davros}
    - save-var-lib-liquid-template
