---
- name: Install the server version of the Liquid Investigations toolkit
  hosts: local
  vars_files:
    - ['vars/defaults.yml', 'vars/config.yml']
  roles:
    - common
    - devel
    - liquid-core
    - hypothesis
