---
- name: Create the top folder
  file: path=/opt/liquid-core state=directory mode=0755

- name: Download the source code
  git: repo=https://github.com/liquidinvestigations/core.git
       dest=/opt/liquid-core/liquid-core

- name: Install requirements
  pip:
    requirements: /opt/liquid-core/liquid-core/requirements.txt
    virtualenv: /opt/liquid-core/venv
    virtualenv_python: python3

- name: Create the var folder
  file:
    path: /opt/liquid-core/var
    state: directory

- name: Change ownership of var folder
  file:
    path: /opt/liquid-core/var
    state: directory
    recurse: yes
    owner: liquid

- name: Create dummy configuration file
  file: state=touch
        dest=/opt/liquid-core/liquid-core/liquidcore/site/settings/local.py

- name: Collect django static files
  shell: ../venv/bin/python ./manage.py collectstatic --noinput
  args:
    chdir: /opt/liquid-core/liquid-core

- name: Run migrations
  shell: ../venv/bin/python ./manage.py migrate
  args:
    chdir: /opt/liquid-core/liquid-core

- name: Remove dummy configuration file
  file: state=absent
        dest=/opt/liquid-core/liquid-core/liquidcore/site/settings/local.py

- name: Link the configuration file
  file: state=link force=yes
        src=/var/lib/liquid/conf/liquid-core/settings.py
        dest=/opt/liquid-core/liquid-core/liquidcore/site/settings/local.py

- name: Create the libexec folder
  file: path=/opt/liquid-core/libexec state=directory mode=0755

- name: Create the runserver script
  template: src=libexec/runserver
            dest=/opt/liquid-core/libexec/runserver
            mode=755

- name: Create the h_user_create script
  template: src=libexec/h_user_create
            dest=/opt/liquid-core/libexec/h_user_create
            mode=755

- name: Create the h_user_passwd script
  template: src=libexec/h_user_passwd
            dest=/opt/liquid-core/libexec/h_user_passwd
            mode=755

- name: Create the h_user_delete script
  template: src=libexec/h_user_delete
            dest=/opt/liquid-core/libexec/h_user_delete
            mode=755
