---
- name: Create the top folder
  file:
    path: /opt/liquid-core
    state: directory
    mode: 0755

- name: Download the source code
  git:
    repo: https://github.com/liquidinvestigations/core.git
    dest: /opt/liquid-core/liquid-core
    version: "{{ git_repo_versions.liquid_core }}"

- name: Create the configuration file
  template:
    src: local.py
    dest: /opt/liquid-core/liquid-core/liquidcore/site/settings/local.py
    mode: 0755
  tags:
    - configure configure-apps

- name: Create the secret_key file
  copy:
    src: secret_key.py
    dest: /opt/liquid-core/liquid-core/liquidcore/site/settings/secret_key.py
    mode: 0755

- name: Install requirements
  pip:
    requirements: /opt/liquid-core/liquid-core/requirements.txt
    virtualenv: /opt/liquid-core/venv
    virtualenv_python: python3

- name: Create the var folder
  file:
    path: /opt/liquid-core/var
    state: directory
    owner: liquid-apps

- name: Collect django static files
  shell: ../venv/bin/python ./manage.py collectstatic --noinput
  args:
    chdir: /opt/liquid-core/liquid-core

- name: Create the libexec folder
  file:
    path: /opt/liquid-core/libexec
    state: directory
    mode: 0755

- name: Create the manage script
  copy:
    src: libexec/manage
    dest: /opt/liquid-core/libexec/manage
    mode: 0755

- name: Create the runserver script
  template:
    src: libexec/runserver
    dest: /opt/liquid-core/libexec/runserver
    mode: 0755

- name: Create the create-oauth-application script
  template:
    src: libexec/create-oauth-application
    dest: /opt/liquid-core/libexec/create-oauth-application
    mode: 0755

- name: Create the supervisor configuration file
  template:
    src: supervisor/liquid-core.conf
    dest: /etc/supervisor/conf.d/liquid-core.conf

- name: Create the nginx configuration file
  template:
    src: nginx/liquid-core.conf
    dest: /etc/nginx/sites-enabled/liquid-core.conf
  tags:
    - configure

- name: Create /var/lib/liquid directories
  file:
    path: "{{ item }}"
    state: directory
    owner: liquid-apps
    group: liquid-apps
    mode: 0700
  with_items:
    - /var/lib/liquid/oauth_keys
    - /var/lib/liquid/core
    - /var/lib/liquid/core/logs

- name: Create the first boot script script
  template:
    src: first-boot.d/liquid-core.sh
    dest: /opt/common/hooks/first-boot.d/00-liquid-core.sh
    mode: 0755

- name: Create the script that creates the users on initialize
  template:
    src: initialize.d/liquid-core-create-users.sh
    dest: /opt/common/initialize.d/95-liquid-core-initial-users.sh
    mode: 0755

- name: Create the script that marks welcome as done
  template:
    src: initialize.d/liquid-core-mark-welcome-done.sh
    dest: /opt/common/initialize.d/99-liquid-core-mark-welcome-done.sh
    mode: 0755
