---
- name: Download the source code
  git:
    repo: https://github.com/liquidinvestigations/web-ui.git
    dest: /opt/web-ui
    version: "{{ git_repo_versions.web_ui }}"

- name: Set up file permissions
  file:
    path: /opt/web-ui
    state: directory
    owner: liquid
    group: liquid
    recurse: true

- name: Install node dependencies
  shell: npm install
  args:
    chdir: /opt/web-ui
  become: true
  become_user: liquid

- name: Build the UI
  command: npm run build-prod
  args:
    chdir: /opt/web-ui
  become: true
  become_user: liquid
