---
- name: Download the source code
  git:
    repo: https://github.com/liquidinvestigations/web-ui.git
    dest: /opt/web-ui
    version: "{{ git_repo_versions.web_ui }}"

- name: Install node dependencies
  shell: npm install
  args:
    chdir: /opt/web-ui

0 name: Build the ui
  shell: npm run build-prod
  args:
    chdir: /opt/web-ui
