---
- name: Download the web-ui source code
  git:
    repo: https://github.com/liquidinvestigations/web-ui.git
    dest: /opt/web-ui
    version: "{{ git_repo_versions.web_ui }}"

- name: Clone the ui-templates repo
  git:
    repo: https://github.com/liquidinvestigations/ui-templates.git
    dest: /opt/ui-templates
    version: "{{ git_repo_versions.ui_templates }}"

- name: Web UI dist artifacts
  unarchive:
    src: https://jenkins.liquiddemo.org/job/liquidinvestigations/job/web-ui/job/master/lastSuccessfulBuild/artifact/web-ui-dist.tar.gz
    dest: /opt/web-ui
    remote_src: yes
    creates: /opt/web-ui/dist

- name: Set up file permissions
  file:
    path: "{{ item }}"
    state: directory
    owner: liquid
    group: liquid
    recurse: true
  with_items:
    - /opt/web-ui
    - /opt/ui-templates
