---
- name: Download the source code
  git:
    repo: https://github.com/liquidinvestigations/web-ui.git
    dest: /opt/web-ui
    version: "{{ git_repo_versions.web_ui }}"

- name: Set up file permissions
  file:
    path: /opt/web-ui
    state: directory
    owner: liquid
    group: liquid
    recurse: true

- name: Web UI dist artifacts
  unarchive:
    src: https://jenkins.liquiddemo.org/__images__/web-ui/web-ui-dist-20171017.tgz
    dest: /opt/web-ui
    remote_src: yes
    creates: /opt/web-ui/dist
