---
- name: Set up directories
  file:
    path: "{{ item }}"
    state: directory
    owner: liquid
    group: liquid
    recurse: true
  with_items:
    - /opt/ui
    - /opt/ui/web-ui
    - /opt/ui/ui-templates

- name: Download the web-ui source code
  git:
    repo: https://github.com/liquidinvestigations/web-ui.git
    dest: /opt/ui/web-ui
    version: "{{ git_repo_versions.web_ui }}"
  become: yes
  become_user: liquid

- name: Download the ui-templates source code
  git:
    repo: https://github.com/liquidinvestigations/ui-templates.git
    dest: /opt/ui/ui-templates
    version: "{{ git_repo_versions.ui_templates }}"
  become: yes
  become_user: liquid

- name: Web UI dist artifacts
  unarchive:
    src: https://jenkins.liquiddemo.org/job/liquidinvestigations/job/web-ui/job/master/lastSuccessfulBuild/artifact/web-ui-dist.tar.gz
    dest: /opt/ui/web-ui
    remote_src: yes
    creates: /opt/ui/web-ui/dist
  become: yes
  become_user: liquid

- name: Create the common install-templates script
  copy:
    src: initialize.d/install-templates
    dest: /opt/common/initialize.d/70-install-templates.py
    mode: 0755
