---
- name: Install discovery-related packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - avahi-daemon
    - avahi-utils
    - libnss-mdns
    - dnsmasq

- name: Configure avahi-daemon
  template:
    src: avahi/avahi-daemon.conf
    dest: /etc/avahi/avahi-daemon.conf

- name: Create avahi-daemon service
  template:
    src: avahi/liquid.service
    dest: /etc/avahi/services/liquid.service

- name: Don't run dnsmasq as system service
  service:
    name: dnsmasq
    enabled: no
    state: stopped

- name: Create the /opt/discover folder
  file:
    path: /opt/discover
    state: directory
    mode: 0755

- name: Download the source code
  git:
    repo: https://github.com/liquidinvestigations/discover.git
    dest: /opt/discover/discover

- name: Create the configuration file
  template:
    src: local.py
    dest: /opt/discover/discover/settings/local.py
    mode: 755

- name: Install requirements for discover
  pip:
    requirements: /opt/discover/discover/requirements.txt
    virtualenv: /opt/discover/venv
    virtualenv_python: python3

- name: Create the libexec folder
  file:
    path: /opt/discover/libexec
    state: directory
    mode: 0755

- name: Create the runserver script
  template:
    src: libexec/runserver
    dest: /opt/discover/libexec/runserver
    mode: 755

- name: Create the supervisor conf for discover
  template:
    src: supervisor/discover.conf
    dest: /etc/supervisor/conf.d/discover.conf

- name: Create the supervisor conf for dnsmasq-dns
  template:
    src: supervisor/dnsmasq-dns.conf
    dest: /etc/supervisor/conf.d/dnsmasq-dns.conf

- name: Create /var/lib/liquid/conf directory
  file:
    path: /var/lib/liquid/conf
    state: directory

- name: Create /var/lib/liquid/conf/discover directory
  file:
    path: /var/lib/liquid/conf/discover
    state: directory

- name: Create /var/lib/liquid/conf/discover/dnsmasq.conf file
  file:
    path: /var/lib/liquid/conf/discover/dnsmasq.conf
    state: touch
