---
- name: Install discovery-related packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - avahi-daemon
    - avahi-utils
    - libnss-mdns
    - dnsmasq
    - python3-dev

- name: Configure avahi-daemon
  template:
    src: avahi/avahi-daemon.conf
    dest: /etc/avahi/avahi-daemon.conf

- name: Create avahi-daemon service
  template:
    src: avahi/liquid.service
    dest: /etc/avahi/services/liquid.service

- name: Don't run dnsmasq as system service
  service:
    name: dnsmasq
    enabled: no

- name: Create the /opt/discover folder
  file:
    path: /opt/discover
    state: directory
    mode: 0755

- name: Download the source code
  git:
    repo: https://github.com/liquidinvestigations/discover.git
    dest: /opt/discover/discover
    version: "{{ git_repo_versions.discover }}"

- name: Touch the secret_key.py config for discover
  file:
    dest: /opt/discover/discover/settings/secret_key.py
    owner: liquid
    group: liquid
    state: touch

- name: Create the configuration file
  template:
    src: local.py
    dest: /opt/discover/discover/settings/local.py

- name: Install requirements for discover
  pip:
    requirements: /opt/discover/discover/requirements.txt
    virtualenv: /opt/discover/venv
    virtualenv_python: python3

- name: Create the libexec folder
  file:
    path: /opt/discover/libexec
    state: directory
    mode: 0755

- name: Create the runserver script
  template:
    src: libexec/runserver
    dest: /opt/discover/libexec/runserver
    mode: 0755

- name: Create the initialization script
  copy:
    src: initialize.d/discover.sh
    dest: /opt/common/initialize.d/25-discover.sh
    mode: 0755

- name: Create the supervisor conf for discover
  template:
    src: supervisor/discover.conf
    dest: /etc/supervisor/conf.d/discover.conf

- name: Create /var/lib/liquid/conf/discover directory
  file:
    path: /var/lib/liquid/conf/discover
    state: directory

- name: Create /var/lib/liquid/conf/discover/dnsmasq.conf file
  file:
    path: /var/lib/liquid/conf/discover/dnsmasq.conf
    state: touch

- name: Don't enable avahi-daemon as a system service
  service:
    name: avahi-daemon
    enabled: no

- name: Use localhost as first nameserver
  lineinfile:
    line: 'nameserver 127.0.0.1'
    state: present
    path: /etc/resolvconf/resolv.conf.d/head
