---
- name: Install discovery-related packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - avahi-daemon
    - avahi-utils
    - libnss-mdns
    - dnsmasq
    - python3-dev

- name: Clear the system avahi-daemon service dir
  file:
    state: absent
    path: /etc/avahi/services

- name: Link the avahi-daemon service dir
  file:
    state: link
    force: yes
    src: /var/lib/liquid/conf/discover/services
    dest: /etc/avahi/services

- name: Don't run dnsmasq as system service
  service:
    name: dnsmasq
    enabled: no

- name: Create the /opt/discover folder
  file:
    path: /opt/discover
    state: directory
    mode: 0755

- name: Download the source code
  git:
    repo: https://github.com/liquidinvestigations/discover.git
    dest: /opt/discover/discover

- name: Link the configuration file
  file:
    state: link
    force: yes
    src: /var/lib/liquid/conf/discover/settings.py
    dest: /opt/discover/discover/settings/local.py

- name: Install requirements for discover
  pip:
    requirements: /opt/discover/discover/requirements.txt
    virtualenv: /opt/discover/venv
    virtualenv_python: python3

- name: Create the libexec folder
  file:
    path: /opt/discover/libexec
    state: directory
    mode: 0755

- name: Create the runserver script
  template:
    src: libexec/runserver
    dest: /opt/discover/libexec/runserver
    mode: 0755

- name: Create /var/lib/liquid/conf/discover directory
  file:
    path: /var/lib/liquid/conf/discover
    state: directory

- name: Create /var/lib/liquid/conf/discover/dnsmasq.conf file
  file:
    path: /var/lib/liquid/conf/discover/dnsmasq.conf
    state: touch

- name: Don't enable avahi-daemon as a system service
  service:
    name: avahi-daemon
    enabled: no
    state: stopped
