---
- when: ansible_architecture == 'x86_64'
  block:
  - name: Import GPG key
    apt_key:
      url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
      id: "68576280"
      state: present

  - name: Add apt source
    apt_repository:
      repo: 'deb https://deb.nodesource.com/node_6.x {{ ansible_distribution_release }} main'
      state: present

  - name: Install nodejs
    apt:
      pkg:
        - nodejs=6.*
      state: installed
  tags:
    - prerequisites

- when: ansible_architecture == 'aarch64'
  block:
  - name: Create node_6.x folder
    file:
      path: /opt/node_6.x
      state: directory
      mode: 0755

  - name: Download nodejs v6.10.2
    unarchive:
      src: https://nodejs.org/dist/v6.10.1/node-v6.10.1-linux-arm64.tar.gz
      dest: /opt/node_6.x
      remote_src: yes
      creates: /opt/node_6.x/node-v6.10.1-linux-arm64

  - name: Create symlinks in /usr/local/bin
    file:
      src: /opt/node_6.x/node-v6.10.1-linux-arm64/bin/{{ item }}
      dest: /usr/local/bin/{{ item }}
      state: link
    with_items:
      - node
      - npm
  tags:
    - prerequisites

- when: ansible_architecture == 'armv7l'
  block:
  - name: Create node_6.x folder
    file:
      path: /opt/node_6.x
      state: directory
      mode: 0755

  - name: Download nodejs v6.10.2
    unarchive:
      src: https://nodejs.org/dist/v6.10.1/node-v6.10.1-linux-armv7l.tar.gz
      dest: /opt/node_6.x
      remote_src: yes
      creates: /opt/node_6.x/node-v6.10.1-linux-armv7l

  - name: Create symlinks in /usr/local/bin
    file:
      src: /opt/node_6.x/node-v6.10.1-linux-armv7l/bin/{{ item }}
      dest: /usr/local/bin/{{ item }}
      state: link
    with_items:
      - node
      - npm
  tags:
    - prerequisites
