---

- name: Clone authproxy repo
  git:
    repo: https://github.com/liquidinvestigations/authproxy.git
    dest: /opt/matrix/authproxy

- name: Install authproxy requirements
  pip:
    requirements: /opt/matrix/authproxy/requirements.txt
    virtualenv: /opt/matrix/authproxy/venv
    virtualenv_python: python3

- name: Create authproxy main config
  template:
    src: authproxy/settings.py
    dest: /opt/matrix/authproxy/config/settings.py

- when: liquid_services.matrix.enabled
  name: Copy the initialization script
  template:
    src: initialize.d/authproxy.sh
    dest: /opt/common/initialize.d/20-matrix-authproxy.sh
    mode: 0755
  tags:
    - configure
    - configure-services

- when: not liquid_services.matrix.enabled
  name: Remove configuration files for disabled service
  file:
    path: /opt/common/initialize.d/20-matrix-authproxy.sh
    state: absent
  tags:
    - configure
    - configure-services
