---
- name: Install required packages
  apt: name={{ item }} state=latest
  with_items:
    - build-essential
    - python2.7-dev
    - libffi-dev 
    - python-pip
    - python-setuptools
    - sqlite3 
    - libssl-dev
    - libjpeg-dev
    - libxslt1-dev

- name: Create the matrix folder
  file:
    path: /opt/matrix
    state: directory
    mode: 0755

- name: Subscribe to hooks
  copy:
    src: hooks/user
    dest: /opt/common/hooks/{{ item }}.d/matrix
    mode: 0755
  with_items:
    - user-created

- name: Copy the requirements file
  copy:
    src: requirements.txt
    dest: /opt/matrix/requirements.txt

- name: Install synapse homeserver
  pip:
    requirements: /opt/matrix/requirements.txt
    virtualenv: /opt/matrix/synapse
    virtualenv_python: python2.7

- name: Set up the configuration file
  template:
    src: homeserver.yaml
    dest: /opt/matrix/synapse/homeserver.yaml

- name: Create the initialization script
  copy:
    src: initialize.d/matrix
    dest: /opt/common/initialize.d/matrix
    mode: 0755

- name: Create supervisor config
  copy:
    src: supervisor/matrix.conf
    dest: /etc/supervisor/conf.d/matrix.conf

- name: Create nginx config
  template:
    src: nginx/matrix.conf
    dest: /etc/nginx/sites-enabled/matrix.conf

