---
- when: devel
  block:
    - name: Install development packages
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - tmux
        - dnsutils
        - man
        - tcpdump
        - vim
        - htop
        - zsh
      tags:
        - prerequisites

    - name: Set up a default password for the liquid user
      command: bash -c "echo liquid:liquid | chpasswd"

    - name: Permit password sshd auth
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PasswordAuthentication "
        line: "PasswordAuthentication yes"
