---
- when: devel
  block:
    - name: Install development packages
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - tmux
        - dnsutils
        - man
        - tcpdump
        - vim
        - htop
        - zsh
        - sl
      tags:
        - prerequisites

    - name: Set up a default password for the liquid user
      command: bash -c "echo liquid-admin:liquid | chpasswd"
