#!/bin/bash
set -e
set -x

cd /opt/hoover

# if the testdata collection exists, exit
have_testdata=$(docker-compose run --rm snoop ./manage.py collection | grep testdata | wc -l)
if [[ $have_testdata -ne 0 ]]; then echo "testdata collection already exists"; exit 0; fi

# index the testdata collection
docker-compose run --rm snoop ./manage.py createcollection /opt/hoover/collections/testdata/data testdata testdata "Hoover Test Data" "Hoover Test Data"
docker-compose run --rm snoop ./manage.py walk testdata
docker-compose run --rm snoop ./manage.py digestqueue
docker-compose run --rm snoop /wait-for-it snoop-tika:9998 -t 120 -- ./manage.py worker digest
docker-compose run --rm snoop /wait-for-it search-es:9200 -t 120 -- ./manage.py resetindex testdata
docker-compose run --rm search ./manage.py addcollection testdata http://snoop/testdata/json
docker-compose run --rm search ./manage.py update -v2 testdata
