---
- name: Create folder
  file:
    path: /opt/dokuwiki
    state: directory
    mode: 0755

- when: ansible_architecture == 'x86_64'
  set_fact:
    dokuwiki_docker_tag: 'latest'

- when: ansible_architecture == 'x86_64'
  block:

  - name: Write compose file
    template:
      # `src` is a relative path because this file is included
      # directly from `image_host_docker.yml`, not as a role.
      src: ../templates/docker-compose.yml
      dest: /opt/dokuwiki/docker-compose.yml
      mode: 0644

  - name: Build docker image
    when: build_docker_images
    docker_service:
      project_src: /opt/dokuwiki
      build: true
      stopped: true
