---
- name: Install php and dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - php-fpm
    - php-xml
  tags:
    - prerequisites

- name: Add user liquid-apps to group www-data
  user:
    name: liquid-apps
    groups: www-data
    append: yes
  tags:
    - prerequisites

- name: Find out if dokuwiki is installed
  stat:
    path: /opt/dokuwiki
  register: dokuwiki

- when: dokuwiki.stat.exists == False
  name: Install Dokuwiki
  block:
  - name: Create /opt/dokuwiki directory
    file:
      path: /opt/dokuwiki
      state: directory

  - name: Download DokuWiki stable source code
    shell: "wget https://download.dokuwiki.org/src/dokuwiki/dokuwiki-2017-02-19e.tgz -O - | tar -xzf - -C /opt/dokuwiki --strip 1"

  - name: Create dokuwiki bootstrap template directory
    file:
      path: /opt/dokuwiki/lib/tpl/bootstrap-template
      state: directory

  - name: Download DokuWiki bootstrap template coode
    shell: "wget https://github.com/LotarProject/dokuwiki-template-bootstrap3/tarball/2ae0cefbd25ce2304914bd01e6350d4eb83310f3 -O - | tar -xzf - -C /opt/dokuwiki/lib/tpl/bootstrap-template --strip 1"

  - name: Move dokuwiki to /var/lib/liquid/dokuwiki
    shell: mv /opt/dokuwiki /var/lib/liquid

  - name: Set up file permissions
    file:
      path: /var/lib/liquid/dokuwiki
      state: directory
      owner: www-data
      group: www-data
      recurse: yes
      follow: yes

  - name: Link to new dokuwiki path
    file:
      src: /var/lib/liquid/dokuwiki
      path: /opt/dokuwiki
      state: link
      force: yes
      owner: www-data
      group: www-data


- when: liquid_services.dokuwiki.enabled
  block:
  - name: Create nginx config
    template:
      src: nginx/dokuwiki.conf
      dest: /etc/nginx/sites-enabled/dokuwiki.conf
  
  - name: Create the initialization script
    copy:
      src: initialize.d/dokuwiki
      dest: /opt/common/initialize.d/21-dokuwiki.sh
      mode: 0755
  
  - name: Subscribe to hooks
    copy:
      src: hooks/user
      dest: /opt/common/hooks/{{ item }}.d/dokuwiki
      mode: 0755
    with_items:
      - user-created
      - user-passwd
      - user-deleted
  tags:
    - configure
    - configure-services

- when: not liquid_services.dokuwiki.enabled
  name: Remove configuration files for disabled service
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/nginx/sites-enabled/dokuwiki.conf
    - /opt/common/initialize.d/21-dokuwiki.sh
    - /opt/common/hooks/user-created.d/dokuwiki
    - /opt/common/hooks/user-passwd.d/dokuwiki
    - /opt/common/hooks/user-deleted.d/dokuwiki
  tags:
    - configure
    - configure-services
