---
- name: Install php and dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - php-fpm
    - php-xml

- name: Create /opt/dokuwiki directory
  file:
    path: /opt/dokuwiki
    state: directory

- name: Download DokuWiki stable source code
  shell: "wget https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz -O - | tar -xzvf - -C /tmp/doku --strip 1"

- name: Set up file permissions
  file:
    path: /opt/dokuwiki
    state: directory
    owner: liquid
    group: liquid
    recurse: true

- name: Create nginx config
  template:
    src: nginx/dokuwiki.conf
    dest: /etc/nginx/sites-enabled/dokuwiki.conf
  tags:
    - configure

- name: Create the initialization script
  copy:
    src: initialize.d/dokuwiki
    dest: /opt/common/initialize.d/21-dokuwiki.sh
    mode: 0755

- name: Subscribe to hooks
  copy:
    src: hooks/user
    dest: /opt/common/hooks/{{ item }}.d/dokuwiki
    mode: 0755
  with_items:
    - user-created
    - user-passwd
    - user-deleted
