---
- name: Create folder
  file:
    path: /opt/dokuwiki
    state: directory
    mode: 0755

- name: Write compose file
  template:
    src: docker-compose.yml
    dest: /opt/dokuwiki/docker-compose.yml
    mode: 644

- name: Build docker image
  docker_service:
    project_src: /opt/dokuwiki
    build: true
    stopped: true

- name: Create nginx config
  template:
    src: nginx/dokuwiki.conf
    dest: /etc/nginx/sites-enabled/dokuwiki.conf
